### PR TITLE
RoM - scripts fixed

### PR DESCRIPTION
**Pull request by jfcarre**

### CODE REVIEW

**Comment by aremazeilles** [comment]
From this branch, when I launch from Octave I get:

```octave
>> addpath("Range_of_movement_octave/src")
>>
>> Main_ROM_LBT_Exo('Range_of_movement_octave/tests/data/input/dinamica56_B.mat', "output")
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 783 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 784 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 785 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 786 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 787 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 788 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 789 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 790 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 791 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 792 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
warning: '...' continuations in double-quoted character strings are obsolete and will not be allowed in a futureversion of Octave; please use '\' instead; near line 793 of file '/home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/ROMAnkle_LBTExo_octave.m'
warning: called from
    Main_ROM_LBT_Exo at line 4 column 32
error: ROMAnkle_LBTExo_octave: =: nonconformant arguments (op1 is 1x1, op2 is 1x0)
error: called from
    ROMAnkle_LBTExo_octave at line 83 column 22
    Main_ROM_LBT_Exo at line 4 column 32
>>
```

The warning is "ok", but I get an error at the end, apparently at line 83 of `ROMAnkle_LBTExo_octave.m`. This is working with you?

Could it be an issue with Octave version? Mine is  4.2.2. And you?

**Comment by aremazeilles** [comment]
ping

**Comment by aremazeilles** [comment]
Any news?

**Comment by jfcarre** [comment]
I have run again the code on my computer and it is working, the Octave version I used is 6.1.0

**Pull request merged**
