### PR TITLE
Range of Movement - Output Format Modifications

### PR DESCRIPTION
**Pull request by jfcarre**
I have modified the files in the folder "Range of Movement". Please, check if the output format is correct.  The modifications with respect to the previous code include: 
   - Each previous script has been converted into a function that is called from a "Main_ROM_XXX" file.
   - In the folder: tests/data/output the existing files have been moved to the folder "NO", and the output of the new code has been placed instead
   - In the TODO file, specific information about To-Do tasks and errors founded has been added.

### CODE REVIEW

**Comment by aremazeilles** [comment]
The best way to request  review, is to assign the Pull request to someone (upper right).

Do you expect me to do so?

**Comment by aremazeilles** [comment]
This is the arrea named "assignees"

**Comment by aremazeilles** [comment]
>  El output de cada experimento (Sagittal Lifting, LBT con Exo, LBT sin Exo) sería un archivo .yaml que incluiría un vector de vectores, cada uno conteniendo la información sobre el ROM de una articulación en específico.

The yaml output format sounds good. It would be great although to add a retuen after the vector ("\n" symbol")
Some PI seems quite long. It is complex to see how two experiments could be compared given such long metric (vectr_of_vector), but this may not be the most urgent aspect to look at.

As is indicated in the "Files Changed" (above), 33 fiels are modified. As I did not start revising the code, I think this could be just merged.

Then, we should a select a metric (range of movement for instance), and bring it to the eurobench format. I would suggest referring to the structure used in  https://github.com/AdrianaTorres/Irregular_Terrains, as we are likely to reproduce it.

So I am waiting for you answer to (1) merge this PR, (2) confirm that we focus on `range_of_movement`.
Then I would suggest to look at irregular terrain as an example, and contact me if you do not see how to shape your code to be compliant.

**Comment by aremazeilles** [comment]
So I guess I can merge it, right?

**Comment by jfcarre** [comment]
> > El output de cada experimento (Sagittal Lifting, LBT con Exo, LBT sin Exo) sería un archivo .yaml que incluiría un vector de vectores, cada uno conteniendo la información sobre el ROM de una articulación en específico.
> 
> The yaml output format sounds good. It would be great although to add a retuen after the vector ("\n" symbol")
> Some PI seems quite long. It is complex to see how two experiments could be compared given such long metric (vectr_of_vector), but this may not be the most urgent aspect to look at.
> 
> As is indicated in the "Files Changed" (above), 33 fiels are modified. As I did not start revising the code, I think this could be just merged.
> 
> Then, we should a select a metric (range of movement for instance), and bring it to the eurobench format. I would suggest referring to the structure used in https://github.com/AdrianaTorres/Irregular_Terrains, as we are likely to reproduce it.
> 
> So I am waiting for you answer to (1) merge this PR, (2) confirm that we focus on `range_of_movement`.
> Then I would suggest to look at irregular terrain as an example, and contact me if you do not see how to shape your code to be compliant.

I will add the return in further modifications and yes, I think the code can be merged without any problem. Regarding the PI, yes, we are focusing on `range_of_movement`, and the modifications implemented are all regarding the Eurobench format. As you are proposing, I have already taken a look at the code in Irregular Terrain and I would like you to confirm that the code and the files in `range_of_movement` fulfills the requirements of format and organization.

**Pull request merged**
